### ISSUE TITLE
TypeError: s.triggerCharacters is not iterable

### ISSUE THREAD

**Issue by karimknaebel** [neoclide/coc-vimtex#2]
```
2019-02-24T15:54:29.712 ERROR (pid:15194) [completion] - TypeError: s.triggerCharacters is not iterable
    at Sources.getTriggerCharacters (/snapshot/coc.nvim/lib/sources.js:229:29)
    at Completion._doComplete (/snapshot/coc.nvim/lib/completion/index.js:205:51)
    at Completion.startCompletion (/snapshot/coc.nvim/lib/completion/index.js:129:24)
    at Completion.triggerCompletion (/snapshot/coc.nvim/lib/completion/index.js:311:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2019-02-24T15:54:31.213 ERROR (pid:15194) [completion] - TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Sources.getTriggerCharacters (/snapshot/coc.nvim/lib/sources.js:229:29)
    at Completion._doComplete (/snapshot/coc.nvim/lib/completion/index.js:205:51)
    at Completion.startCompletion (/snapshot/coc.nvim/lib/completion/index.js:129:24)
    at Completion.triggerCompletion (/snapshot/coc.nvim/lib/completion/index.js:311:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by karimknaebel** [comment]
vimtex plugin is installed

**Comment by karimknaebel** [comment]
```
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.56
term: iTerm.app
platform: darwin

## Error messages

## Output channel: snippets
[Info 2019-2-24] Loaded 20 snippets from /Users/karim/.config/coc/extensions/node_modules/coc-java/snippets/java.json

## Output channel: highlight
[Info  - 15:53:57] Highlight server running in node v8.9.0

```

**Comment by karimknaebel** [comment]
Building `master` form source fixed the issue.

**Comment by wookayin** [comment]
I am using the latest coc.nvim 0.57 (this coc.nvim release fixes this issue) and the latest coc-vimtex, but still having the issue. @kabouzeid How and what did you build?

**Comment by karimknaebel** [comment]
`Plug 'neoclide/coc.nvim', {'tag': '*', 'do': 'yarn install'}`

Assuming you have yarn installed.

**Comment by wookayin** [comment]
Yeah, it works. Thanks! :)

**Comment by karimknaebel** [comment]
Awesome, glad to help :)
